version: "3.9"

services:
  server:
    build:
      context: ./simple-server/.
      dockerfile: ./Dockerfile
    # environment:
    #   QUICKFIXJ_SERVER_CONFIG_FILE: "file:/opt/app/quickfixj-server.cfg"
    volumes:
      # - ./configs/quickfixj-server.cfg:/opt/app/quickfixj-server.cfg
      - server-logs:/tmp/logs
      - server-data:/opt/app/target/data/executor
    networks:
      - net

  client:
    build:
      context:  ./simple-client/.
      dockerfile: ./Dockerfile
    # environment:
    #   QUIICKFIXJ_CLIENT_CONFIG_FILE: "file:/opt/app/quickfixj-client.cfg"
    # ports:
    #   - 8081:8081
    volumes:
      # - ./configs/quickfixj-client.cfg:/opt/app/quickfixj-client.cfg
      - client-logs:/tmp/logs
      - client-data:/opt/app/target/data/banzai
    networks:
      - net

volumes:
  server-logs:
  server-data:
  client-logs:
  client-data:

networks:
  net:
