version: "3.9"

services:
  server:
    build:
      context: ./simple-server/.
      dockerfile: ./Dockerfile
    volumes:
      - server-logs:/tmp/logs
      - server-data:/opt/app/target/data/executor
    networks:
      - net

  client:
    build:
      context:  ./simple-client/.
      dockerfile: ./Dockerfile
    volumes:
      - client-logs:/tmp/logs
      - client-data:/opt/app/target/data/banzai
    networks:
      - net

volumes:
  server-logs:
  server-data:
  client-logs:
  client-data:

networks:
  net:
